// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SweetWorld.Infrastructure.Data;

#nullable disable

namespace SweetWorld.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240419201146_Product")]
    partial class Product
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1dcab376-7fa5-4514-8528-c0bc09e12627",
                            ConcurrencyStamp = "581cd48b-1170-4270-abcd-3621c9957fbc",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "fe6c24e5-83c3-43bb-9c8a-21b7338c6af6",
                            ConcurrencyStamp = "5cf95cc2-e01e-4863-aa10-a75cb473cc80",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = "bde985f1-7ae2-4da7-a2b3-afc16ad1c528",
                            ConcurrencyStamp = "f84df18c-ddce-4445-b6ee-f9b0f82014c6",
                            Name = "Confectioner",
                            NormalizedName = "CONFECTIONER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "06f7430b-dfbf-42ed-9618-20f2cfd24875",
                            RoleId = "1dcab376-7fa5-4514-8528-c0bc09e12627"
                        },
                        new
                        {
                            UserId = "7376f12c-855e-40ba-a5d5-d6a993022bf3",
                            RoleId = "fe6c24e5-83c3-43bb-9c8a-21b7338c6af6"
                        },
                        new
                        {
                            UserId = "a501c64b-74f7-46b7-a938-bda911a77b81",
                            RoleId = "fe6c24e5-83c3-43bb-9c8a-21b7338c6af6"
                        },
                        new
                        {
                            UserId = "bb7750b4-cc79-4361-a63b-dd4ad4a9e53f",
                            RoleId = "bde985f1-7ae2-4da7-a2b3-afc16ad1c528"
                        },
                        new
                        {
                            UserId = "ca99e01c-6a19-45a2-9ac2-89f17f79dd08",
                            RoleId = "bde985f1-7ae2-4da7-a2b3-afc16ad1c528"
                        },
                        new
                        {
                            UserId = "0dcee1c1-7ac3-4e14-9e43-77f8c85dae75",
                            RoleId = "bde985f1-7ae2-4da7-a2b3-afc16ad1c528"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.CartOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additional_information");

                    b.Property<int?>("Amount")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("product_amount");

                    b.Property<Guid?>("ClientId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_id");

                    b.Property<Guid?>("ProductId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductThumb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_thumbnail");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_type");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("46371267-0d7c-4e7a-a64f-8716972f0f54"),
                            Name = "French pastries"
                        },
                        new
                        {
                            Id = new Guid("bd6b7990-7394-4c6e-af12-981ac6e2d28b"),
                            Name = "Italian pastries"
                        },
                        new
                        {
                            Id = new Guid("a313707e-4307-4e0e-91b9-5ecd4399931f"),
                            Name = "Muffins"
                        },
                        new
                        {
                            Id = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            Name = "Cakes"
                        },
                        new
                        {
                            Id = new Guid("85901598-c0eb-49ac-93d7-8e680de25a68"),
                            Name = "Cookies"
                        });
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Client", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa6c6780-40d5-4c7e-9e48-fd82d03190b5"),
                            UserId = "7376f12c-855e-40ba-a5d5-d6a993022bf3"
                        },
                        new
                        {
                            Id = new Guid("c96d52c3-571e-4381-a724-b88c58492caa"),
                            UserId = "a501c64b-74f7-46b7-a938-bda911a77b81"
                        });
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Confectioner", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("confectioners", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2b8a345-064a-4381-ab50-70724003fcbd"),
                            UserId = "bb7750b4-cc79-4361-a63b-dd4ad4a9e53f"
                        },
                        new
                        {
                            Id = new Guid("0c10b01e-1b74-48fb-ab1f-7577c7c837de"),
                            UserId = "ca99e01c-6a19-45a2-9ac2-89f17f79dd08"
                        },
                        new
                        {
                            Id = new Guid("cec94c18-629d-4491-8b26-dee405de2cfd"),
                            UserId = "0dcee1c1-7ac3-4e14-9e43-77f8c85dae75"
                        });
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.FavouriteProduct", b =>
                {
                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_id");

                    b.HasKey("ProductId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("favourite_products", (string)null);
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Image", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ProductId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Ingredient", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d62340b8-b340-4765-a289-cc4ec987e23a"),
                            Name = "wipping cream"
                        },
                        new
                        {
                            Id = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            Name = "flour"
                        },
                        new
                        {
                            Id = new Guid("ac441ba7-a0ff-4f44-84e8-3c11b8430c73"),
                            Name = "dark chocolate"
                        },
                        new
                        {
                            Id = new Guid("19c410e1-f574-4e2e-b235-51906d01c727"),
                            Name = "white chocolate"
                        },
                        new
                        {
                            Id = new Guid("5df10646-eaea-4040-b50c-393cf49ca75e"),
                            Name = "seasonal fruit"
                        },
                        new
                        {
                            Id = new Guid("7d52d73e-b4e5-45f6-999e-9e7bd42e8a93"),
                            Name = "strawberries"
                        },
                        new
                        {
                            Id = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            Name = "eggs"
                        },
                        new
                        {
                            Id = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            Name = "sugar"
                        },
                        new
                        {
                            Id = new Guid("cb3fc820-bf1d-4eee-a6c4-a9183618283a"),
                            Name = "milk"
                        },
                        new
                        {
                            Id = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            Name = "butter"
                        },
                        new
                        {
                            Id = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            Name = "baking powder"
                        },
                        new
                        {
                            Id = new Guid("ae5e95cb-f722-4460-8f07-29d58df97a55"),
                            Name = "cocoa"
                        },
                        new
                        {
                            Id = new Guid("775e23ed-1fb6-4125-b23c-c43cb98fe1b6"),
                            Name = "honey"
                        },
                        new
                        {
                            Id = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            Name = "vanilla"
                        },
                        new
                        {
                            Id = new Guid("8e394b57-2c7a-42a1-b700-263d57f8cc5e"),
                            Name = "jam"
                        },
                        new
                        {
                            Id = new Guid("e880c006-3af2-4d28-b8a4-7684cb986185"),
                            Name = "walnuts"
                        },
                        new
                        {
                            Id = new Guid("16fe2f69-513c-4277-af3d-52b641fe9487"),
                            Name = "water"
                        },
                        new
                        {
                            Id = new Guid("662c546d-3e05-4cb4-a392-682cb3fed443"),
                            Name = "sunflower oil"
                        },
                        new
                        {
                            Id = new Guid("287e7803-b225-4131-b7f4-e3b57de672af"),
                            Name = "red food coloring"
                        },
                        new
                        {
                            Id = new Guid("1776e340-9db2-453a-b29f-947b732796cc"),
                            Name = "lemon juice"
                        },
                        new
                        {
                            Id = new Guid("c067592d-7db2-476b-8216-da94a089b269"),
                            Name = "puff pastry"
                        },
                        new
                        {
                            Id = new Guid("701c2a97-48ac-4781-8a08-c60c6aa3f040"),
                            Name = "oat flakes"
                        },
                        new
                        {
                            Id = new Guid("5f89b69f-ee79-488e-bd01-9527b101493a"),
                            Name = "spelt flour"
                        },
                        new
                        {
                            Id = new Guid("be3ebdea-a67c-4a28-b83e-c238cb85c09d"),
                            Name = "coconut oil"
                        },
                        new
                        {
                            Id = new Guid("6ad109c5-e8e7-4f40-8c0e-434f272db285"),
                            Name = "cinnamon"
                        },
                        new
                        {
                            Id = new Guid("ac3d8343-895b-4805-aaeb-3b0d2f9de96a"),
                            Name = "banana"
                        },
                        new
                        {
                            Id = new Guid("0955c74b-8e3c-4ad6-97fc-bdc72c4a70f2"),
                            Name = "chickpeas"
                        },
                        new
                        {
                            Id = new Guid("ad8bddfd-a20d-4f5b-b53b-86e008dc3fc1"),
                            Name = "peanut butter"
                        },
                        new
                        {
                            Id = new Guid("5a35c906-4373-43ef-a4c5-316058e22536"),
                            Name = "brown sugar"
                        },
                        new
                        {
                            Id = new Guid("65009db2-6a67-470e-951b-b9dfd68109f8"),
                            Name = "rice flour"
                        },
                        new
                        {
                            Id = new Guid("26e2241b-5ef0-4998-bf81-3be8b5c5dd64"),
                            Name = "almond flour"
                        },
                        new
                        {
                            Id = new Guid("59a4a752-8e59-4cc9-a5f2-5b52f5e998ca"),
                            Name = "corn flour"
                        },
                        new
                        {
                            Id = new Guid("05810086-be70-48b4-a40c-0330ebea7f7e"),
                            Name = "grape seed oil"
                        },
                        new
                        {
                            Id = new Guid("d8acfa7d-2e90-4fc3-a2a0-89441d7866c2"),
                            Name = "orange essential oil"
                        },
                        new
                        {
                            Id = new Guid("25464223-7321-45e1-a377-e3d3bc9a1a70"),
                            Name = "avocado"
                        },
                        new
                        {
                            Id = new Guid("2d8b869c-ef64-44d9-807a-1221ff08e3b9"),
                            Name = "stevia"
                        },
                        new
                        {
                            Id = new Guid("d90013c0-3372-4dce-8376-9d50e1952a0d"),
                            Name = "apple"
                        },
                        new
                        {
                            Id = new Guid("1c73c664-4242-467f-a13f-5816ed222b97"),
                            Name = "carob flour"
                        });
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additional_information");

                    b.Property<int?>("Amount")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("product_amount");

                    b.Property<Guid?>("ClientId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_creating");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("delivery_address");

                    b.Property<Guid?>("ProductId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPrice")
                        .IsRequired()
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("total_price");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProductId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConfectionerId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("confectioner_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("price");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ConfectionerId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628"),
                            ConfectionerId = new Guid("cec94c18-629d-4491-8b26-dee405de2cfd"),
                            Name = "French village cake",
                            Thumbnail = "https://parmy.bg/media/cache/48/a6/thumb7_IMG_9075.jpg",
                            Type = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f"),
                            ConfectionerId = new Guid("0c10b01e-1b74-48fb-ab1f-7577c7c837de"),
                            Name = "Eclair cake",
                            Thumbnail = "https://local.deweys.com/uploads/1/3/0/7/130725445/s190270156824480679_p237_i3_w1200.png",
                            Type = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102"),
                            ConfectionerId = new Guid("e2b8a345-064a-4381-ab50-70724003fcbd"),
                            Name = "Red velvet cake",
                            Thumbnail = "https://pabalefoodandbeverage.in/wp-content/uploads/2024/03/Red-Velvet-Cake.jpg",
                            Type = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b"),
                            ConfectionerId = new Guid("cec94c18-629d-4491-8b26-dee405de2cfd"),
                            Name = "Red velvet cake with strawberries",
                            Thumbnail = "https://tiffanysbakeryphilly.com/media/catalog/category/RedVelvetStrawberryShortcake_2_1.jpg",
                            Type = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa"),
                            ConfectionerId = new Guid("0c10b01e-1b74-48fb-ab1f-7577c7c837de"),
                            Name = "Napoleon cake",
                            Thumbnail = "https://i.ytimg.com/vi/Q78skleBhp4/maxresdefault.jpg",
                            Type = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5"),
                            ConfectionerId = new Guid("e2b8a345-064a-4381-ab50-70724003fcbd"),
                            Name = "Vanilla cake",
                            Thumbnail = "https://www.gratefulbites.org/wp-content/uploads/2018/02/VanillaVanillaCake.jpg",
                            Type = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb"),
                            ConfectionerId = new Guid("cec94c18-629d-4491-8b26-dee405de2cfd"),
                            Name = "Chocolate cake",
                            Thumbnail = "https://womenfitnessmag.com/wp-content/uploads/2020/07/Delight-Your-Mood-with-Thes.jpg",
                            Type = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2"),
                            ConfectionerId = new Guid("0c10b01e-1b74-48fb-ab1f-7577c7c837de"),
                            Name = "Fruit cake",
                            Thumbnail = "https://www.bakinglikeachef.com/wp-content/uploads/fresh-fruit-cake.jpg",
                            Type = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421"),
                            ConfectionerId = new Guid("e2b8a345-064a-4381-ab50-70724003fcbd"),
                            Name = "Oat honey cookies / 100g",
                            Price = 4.79m,
                            Thumbnail = "https://www.1001recepti.com/images/photos/recipes/size_5/burzi-i-lesni-hrupkavi-vegan-oveseni-medeni-biskviti-6226b8a32b975ab20669e6628c9141ff-[111258].jpg",
                            Type = "Vegan"
                        },
                        new
                        {
                            Id = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf"),
                            ConfectionerId = new Guid("cec94c18-629d-4491-8b26-dee405de2cfd"),
                            Name = "Muffin with cocoa and banana",
                            Price = 2.99m,
                            Thumbnail = "https://www.1001recepti.com/images/photos/recipes/size_5/postni-vegan-mufini-s-kakao-i-banani-bez-iaica-i-bez-mliako-s-voda-1b5449a4c452597988873d251670172f-[108361].jpg",
                            Type = "Vegan"
                        },
                        new
                        {
                            Id = new Guid("3b4feead-b9a6-41e4-b96a-42a50609603d"),
                            ConfectionerId = new Guid("0c10b01e-1b74-48fb-ab1f-7577c7c837de"),
                            Name = "Vegan cookies / 100g",
                            Price = 5.99m,
                            Thumbnail = "https://www.1001recepti.com/images/photos/recipes/size_5/vegan-biskviti-cookies-s-nahut-fustucheno-maslo-i-parchenca-shokolad-79104bbe112c4a8f3bc6c4283ef76bf9-[111257].jpg",
                            Type = "Vegan"
                        },
                        new
                        {
                            Id = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b"),
                            ConfectionerId = new Guid("e2b8a345-064a-4381-ab50-70724003fcbd"),
                            Name = "Chocolate chip cookies / 100g",
                            Price = 4.99m,
                            Thumbnail = "https://images.aws.nestle.recipes/resized/5b069c3ed2feea79377014f6766fcd49_Original_NTH_Chocolate_Chip_Cookie_1080_850.jpg",
                            Type = "Gluten-free"
                        },
                        new
                        {
                            Id = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01"),
                            ConfectionerId = new Guid("cec94c18-629d-4491-8b26-dee405de2cfd"),
                            Name = "Cantuccini with almonds / 100g",
                            Price = 5.19m,
                            Thumbnail = "https://po-krasivi.net/wp-content/uploads/2019/03/kantuchini-recepta-300x201.jpg",
                            Type = "Gluten-free"
                        },
                        new
                        {
                            Id = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f"),
                            ConfectionerId = new Guid("0c10b01e-1b74-48fb-ab1f-7577c7c837de"),
                            Name = "Muffin with avocado",
                            Price = 3.19m,
                            Thumbnail = "https://www.milkandhoneynutrition.com/wp-content/uploads/2020/07/Chocolate-Avocado-Muffins-3.jpg",
                            Type = "Diabetic"
                        });
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.ProductsCategories", b =>
                {
                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("products_categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("46371267-0d7c-4e7a-a64f-8716972f0f54"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            CategoryId = new Guid("46371267-0d7c-4e7a-a64f-8716972f0f54"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            CategoryId = new Guid("46371267-0d7c-4e7a-a64f-8716972f0f54"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            CategoryId = new Guid("bd6b7990-7394-4c6e-af12-981ac6e2d28b"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            CategoryId = new Guid("a313707e-4307-4e0e-91b9-5ecd4399931f"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            CategoryId = new Guid("a313707e-4307-4e0e-91b9-5ecd4399931f"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            CategoryId = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            CategoryId = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            CategoryId = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            CategoryId = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            CategoryId = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            CategoryId = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            CategoryId = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            CategoryId = new Guid("bd90eb3d-e1b9-4308-8cd5-a6c887895ddc"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            CategoryId = new Guid("85901598-c0eb-49ac-93d7-8e680de25a68"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            CategoryId = new Guid("85901598-c0eb-49ac-93d7-8e680de25a68"),
                            ProductId = new Guid("3b4feead-b9a6-41e4-b96a-42a50609603d")
                        },
                        new
                        {
                            CategoryId = new Guid("85901598-c0eb-49ac-93d7-8e680de25a68"),
                            ProductId = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b")
                        },
                        new
                        {
                            CategoryId = new Guid("85901598-c0eb-49ac-93d7-8e680de25a68"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        });
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.ProductsIngredients", b =>
                {
                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ingredient_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.HasKey("IngredientId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("products_ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("d62340b8-b340-4765-a289-cc4ec987e23a"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("775e23ed-1fb6-4125-b23c-c43cb98fe1b6"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("8e394b57-2c7a-42a1-b700-263d57f8cc5e"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("e880c006-3af2-4d28-b8a4-7684cb986185"),
                            ProductId = new Guid("f5f626f4-9a54-48bc-8cda-e68926a4e628")
                        },
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("d62340b8-b340-4765-a289-cc4ec987e23a"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("ac441ba7-a0ff-4f44-84e8-3c11b8430c73"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("16fe2f69-513c-4277-af3d-52b641fe9487"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("662c546d-3e05-4cb4-a392-682cb3fed443"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("cb3fc820-bf1d-4eee-a6c4-a9183618283a"),
                            ProductId = new Guid("dea18594-de69-4d30-9acd-0f2af621d27f")
                        },
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("d62340b8-b340-4765-a289-cc4ec987e23a"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("1776e340-9db2-453a-b29f-947b732796cc"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("287e7803-b225-4131-b7f4-e3b57de672af"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("ae5e95cb-f722-4460-8f07-29d58df97a55"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("662c546d-3e05-4cb4-a392-682cb3fed443"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("cb3fc820-bf1d-4eee-a6c4-a9183618283a"),
                            ProductId = new Guid("8f2a35c9-e3f5-4361-b393-d9ac177c4102")
                        },
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("d62340b8-b340-4765-a289-cc4ec987e23a"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("1776e340-9db2-453a-b29f-947b732796cc"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("287e7803-b225-4131-b7f4-e3b57de672af"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("ae5e95cb-f722-4460-8f07-29d58df97a55"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("662c546d-3e05-4cb4-a392-682cb3fed443"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("cb3fc820-bf1d-4eee-a6c4-a9183618283a"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("7d52d73e-b4e5-45f6-999e-9e7bd42e8a93"),
                            ProductId = new Guid("4ccaf1dc-9bf9-4f55-beec-cd38bbb4701b")
                        },
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            IngredientId = new Guid("c067592d-7db2-476b-8216-da94a089b269"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            IngredientId = new Guid("cb3fc820-bf1d-4eee-a6c4-a9183618283a"),
                            ProductId = new Guid("5229ab70-1818-42be-b0c2-3b4da48a3caa")
                        },
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("cb3fc820-bf1d-4eee-a6c4-a9183618283a"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("d62340b8-b340-4765-a289-cc4ec987e23a"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("19c410e1-f574-4e2e-b235-51906d01c727"),
                            ProductId = new Guid("defc5f08-42d7-495f-bd66-a762226d29c5")
                        },
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("ae5e95cb-f722-4460-8f07-29d58df97a55"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("16fe2f69-513c-4277-af3d-52b641fe9487"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("d62340b8-b340-4765-a289-cc4ec987e23a"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("ac441ba7-a0ff-4f44-84e8-3c11b8430c73"),
                            ProductId = new Guid("64575b60-9c13-4f54-aee4-20dbf9d1f3cb")
                        },
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("cb3fc820-bf1d-4eee-a6c4-a9183618283a"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("d62340b8-b340-4765-a289-cc4ec987e23a"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("19c410e1-f574-4e2e-b235-51906d01c727"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("ae5e95cb-f722-4460-8f07-29d58df97a55"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("16fe2f69-513c-4277-af3d-52b641fe9487"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("ac441ba7-a0ff-4f44-84e8-3c11b8430c73"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("5df10646-eaea-4040-b50c-393cf49ca75e"),
                            ProductId = new Guid("1824a2d5-1519-4173-b628-6ccee98019b2")
                        },
                        new
                        {
                            IngredientId = new Guid("701c2a97-48ac-4781-8a08-c60c6aa3f040"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            IngredientId = new Guid("be3ebdea-a67c-4a28-b83e-c238cb85c09d"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            IngredientId = new Guid("5f89b69f-ee79-488e-bd01-9527b101493a"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            IngredientId = new Guid("e880c006-3af2-4d28-b8a4-7684cb986185"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            IngredientId = new Guid("775e23ed-1fb6-4125-b23c-c43cb98fe1b6"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            IngredientId = new Guid("6ad109c5-e8e7-4f40-8c0e-434f272db285"),
                            ProductId = new Guid("8d23fc0e-42c7-4a64-8100-63d6cf061421")
                        },
                        new
                        {
                            IngredientId = new Guid("85311af6-ce87-461c-b7ff-699a86eb0b47"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("a95acbbb-6cef-4a7b-a245-7f8d028e0de7"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("662c546d-3e05-4cb4-a392-682cb3fed443"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("6ad109c5-e8e7-4f40-8c0e-434f272db285"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("ae5e95cb-f722-4460-8f07-29d58df97a55"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("16fe2f69-513c-4277-af3d-52b641fe9487"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("ac3d8343-895b-4805-aaeb-3b0d2f9de96a"),
                            ProductId = new Guid("4b856ddb-c40f-404e-9b06-164ebb3755cf")
                        },
                        new
                        {
                            IngredientId = new Guid("0955c74b-8e3c-4ad6-97fc-bdc72c4a70f2"),
                            ProductId = new Guid("3b4feead-b9a6-41e4-b96a-42a50609603d")
                        },
                        new
                        {
                            IngredientId = new Guid("ad8bddfd-a20d-4f5b-b53b-86e008dc3fc1"),
                            ProductId = new Guid("3b4feead-b9a6-41e4-b96a-42a50609603d")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("3b4feead-b9a6-41e4-b96a-42a50609603d")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("3b4feead-b9a6-41e4-b96a-42a50609603d")
                        },
                        new
                        {
                            IngredientId = new Guid("775e23ed-1fb6-4125-b23c-c43cb98fe1b6"),
                            ProductId = new Guid("3b4feead-b9a6-41e4-b96a-42a50609603d")
                        },
                        new
                        {
                            IngredientId = new Guid("ac441ba7-a0ff-4f44-84e8-3c11b8430c73"),
                            ProductId = new Guid("3b4feead-b9a6-41e4-b96a-42a50609603d")
                        },
                        new
                        {
                            IngredientId = new Guid("65009db2-6a67-470e-951b-b9dfd68109f8"),
                            ProductId = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b")
                        },
                        new
                        {
                            IngredientId = new Guid("5a35c906-4373-43ef-a4c5-316058e22536"),
                            ProductId = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b")
                        },
                        new
                        {
                            IngredientId = new Guid("beee5e53-e8ef-4d6e-a113-b449540d398e"),
                            ProductId = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b")
                        },
                        new
                        {
                            IngredientId = new Guid("ae5e95cb-f722-4460-8f07-29d58df97a55"),
                            ProductId = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b")
                        },
                        new
                        {
                            IngredientId = new Guid("ac441ba7-a0ff-4f44-84e8-3c11b8430c73"),
                            ProductId = new Guid("e4dfb73d-8426-4c5e-bade-452c6d43bc3b")
                        },
                        new
                        {
                            IngredientId = new Guid("65009db2-6a67-470e-951b-b9dfd68109f8"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("26e2241b-5ef0-4998-bf81-3be8b5c5dd64"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("59a4a752-8e59-4cc9-a5f2-5b52f5e998ca"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("5a35c906-4373-43ef-a4c5-316058e22536"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("05810086-be70-48b4-a40c-0330ebea7f7e"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("d8acfa7d-2e90-4fc3-a2a0-89441d7866c2"),
                            ProductId = new Guid("8f9967a1-2dd4-4d7e-9160-93da660a3d01")
                        },
                        new
                        {
                            IngredientId = new Guid("25464223-7321-45e1-a377-e3d3bc9a1a70"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("1c73c664-4242-467f-a13f-5816ed222b97"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("2d8b869c-ef64-44d9-807a-1221ff08e3b9"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("d90013c0-3372-4dce-8376-9d50e1952a0d"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("662c546d-3e05-4cb4-a392-682cb3fed443"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("6a76316d-e003-40d4-8d5e-553d6c59747f"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("9216d028-f18e-44d4-b932-2f78719c0cba"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("75879d97-4f7e-4f11-860d-205d63dfb1e9"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("5f89b69f-ee79-488e-bd01-9527b101493a"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        },
                        new
                        {
                            IngredientId = new Guid("6ad109c5-e8e7-4f40-8c0e-434f272db285"),
                            ProductId = new Guid("b21d0d2d-fe21-4080-8f99-d7b61574957f")
                        });
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7376f12c-855e-40ba-a5d5-d6a993022bf3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0cfa859a-30b0-4085-8af9-292eb19488e9",
                            Email = "geritsaneva@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Geri",
                            LastName = "Tsaneva",
                            LockoutEnabled = false,
                            NormalizedEmail = "GERITSANEVA@GMAIL.COM",
                            NormalizedUserName = "GERI88",
                            PasswordHash = "AQAAAAEAACcQAAAAEH6BGedKywb+aDKfYRwi1JOoOQPa0UuzNkNwPxjGtiWs29TA597YjgLrzS86iIHB1w==",
                            PhoneNumber = "0893052673",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bfbf5575-5d57-4a07-a249-916861164fac",
                            TwoFactorEnabled = false,
                            UserName = "geri88"
                        },
                        new
                        {
                            Id = "bb7750b4-cc79-4361-a63b-dd4ad4a9e53f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "71b16834-1066-4727-8678-926c000a0ff8",
                            Email = "kalypo3@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Kaly",
                            LastName = "Malchinikolova",
                            LockoutEnabled = false,
                            NormalizedEmail = "kalypo3@GMAIL.COM",
                            NormalizedUserName = "KALY79",
                            PasswordHash = "AQAAAAEAACcQAAAAEE6gwOEbTy08LGbW6LlWIKWVJsyBJThWth1FNMpD/Wi598iFGboNajgqSaLkCe27AQ==",
                            PhoneNumber = "0888752419",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0682cd05-fd61-4af3-9a4b-17787a956877",
                            TwoFactorEnabled = false,
                            UserName = "kaly79"
                        },
                        new
                        {
                            Id = "06f7430b-dfbf-42ed-9618-20f2cfd24875",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b9d567b6-8957-4fdb-bcef-a4b499400548",
                            Email = "meribelcheva@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Meri",
                            LastName = "Belcheva",
                            LockoutEnabled = false,
                            NormalizedEmail = "MERIBELCHEVA@GMAIL.COM",
                            NormalizedUserName = "MERI05",
                            PasswordHash = "AQAAAAEAACcQAAAAEG0Cy/OPYIrQ3U6wxG7XddiqfnSg7+RRNlfHYIUO4lMT8TwCvcqhD8lbgRizxcq/Uw==",
                            PhoneNumber = "0898508050",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14a5bb9c-60b1-40d0-a70c-6798f4796d06",
                            TwoFactorEnabled = false,
                            UserName = "meri05"
                        },
                        new
                        {
                            Id = "a501c64b-74f7-46b7-a938-bda911a77b81",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "520752a4-a83f-45e7-8e98-e2eb2ca62c60",
                            Email = "hrisimiteva@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Hrisi",
                            LastName = "Miteva",
                            LockoutEnabled = false,
                            NormalizedEmail = "HRISIMITEVA@GMAIL.COM",
                            NormalizedUserName = "HRISI05",
                            PasswordHash = "AQAAAAEAACcQAAAAECQQf/1PpVeTHc9DpxdwAS5Qc8EEwvv8l4GLdG2lHyIiO6fJ4/EFkcOjWX8bacEhdg==",
                            PhoneNumber = "0895719337",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e0bba3a-7f97-42ec-9f9c-46aa34a1e81d",
                            TwoFactorEnabled = false,
                            UserName = "hrisi05"
                        },
                        new
                        {
                            Id = "ca99e01c-6a19-45a2-9ac2-89f17f79dd08",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4bb6b7e-b718-4e90-a730-117f3103ad43",
                            Email = "ognyankirilov@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ognyan",
                            LastName = "Kirilov",
                            LockoutEnabled = false,
                            NormalizedEmail = "OGNYANKIRILOV@GMAIL.COM",
                            NormalizedUserName = "OGNYAN06",
                            PasswordHash = "AQAAAAEAACcQAAAAEAgHj+HpkIOZmcIX3/s2OhkfqSMUmPr6e0vziGwuguoDhWalXZbQ8s/pE9aCd6eV4A==",
                            PhoneNumber = "0897373378",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d9ecfd34-59eb-44b4-924c-2e20bc64ecfc",
                            TwoFactorEnabled = false,
                            UserName = "ognyan06"
                        },
                        new
                        {
                            Id = "0dcee1c1-7ac3-4e14-9e43-77f8c85dae75",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82f796ef-a43b-4ebc-90cc-68ba3efb75ab",
                            Email = "elitsageorgieva@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Elitsa",
                            LastName = "Georgieva",
                            LockoutEnabled = false,
                            NormalizedEmail = "ELITSAGEORGIEVA@GMAIL.COM",
                            NormalizedUserName = "ELITSA89",
                            PasswordHash = "AQAAAAEAACcQAAAAECrWb8Q0tj28Qq7PePIApseix9QMiedOvUCc0vMNjswmdyNa2rfy/HlS/Iflwxb02A==",
                            PhoneNumber = "0896999728",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b31610de-aa8b-4182-82be-ad86c61b93ac",
                            TwoFactorEnabled = false,
                            UserName = "elitsa89"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SweetWorld.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.CartOrder", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Client", "Client")
                        .WithMany("Cart")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Client", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Confectioner", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.FavouriteProduct", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Client", "Client")
                        .WithMany("FavouriteProducts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Image", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Confectioner", "Confectioner")
                        .WithMany("Products")
                        .HasForeignKey("ConfectionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Confectioner");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.ProductsCategories", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("ProductsCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.ProductsIngredients", b =>
                {
                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Ingredient", "Ingredient")
                        .WithMany("ProductsIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SweetWorld.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Ingredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("ProductsCategories");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Client", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("FavouriteProducts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Confectioner", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Ingredient", b =>
                {
                    b.Navigation("ProductsIngredients");
                });

            modelBuilder.Entity("SweetWorld.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("FavoriteProducts");

                    b.Navigation("Images");

                    b.Navigation("Ingredients");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
